# Site settings
title:          Zongquan
description:    "一份坚持，一份收获"
baseurl:        ""
url:            "https://blog.zqai.run/"

# Google Analytics
google_analytics: UA-164558676-1

# Author
author:
  name:         Zongquan
  url:          https://blog.zqai.run/
  email:        aizquan@qq.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       8

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale